In [ ]:
# Importing Necessary Libraries
import torch
import numpy as np

In [2]:
# Converting Lists to Tensors
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
# Converting Numpy Arrays to Tensors
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# Using factory methods to create tensors
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4067, 0.6020],
        [0.3715, 0.2756]])


In [5]:
# Specifying shape for factory methods

shape = (2,3)

x_ones = torch.ones(shape)
print(x_ones)

x_rand = torch.rand(shape)
print(x_rand)

x_zeros = torch.zeros(shape)
print(x_zeros)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6158, 0.1928, 0.1504],
        [0.8808, 0.1421, 0.2620]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# Attributes of a Tensor

print(x_data.shape)
print(x_data.dtype)
print(x_data.device)

torch.Size([2, 2])
torch.int64
cpu


In [7]:
# Cat operation for joining Tensors
tensor = torch.ones(4,4)

# Column Wise Concatenation
print(torch.cat([tensor,tensor,tensor],dim=1))

# Row Wise Concatenation
print(torch.cat([tensor,tensor,tensor],dim=0))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
# Matrix Multiplication

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

m3 = torch.rand_like(y1)
y3 = torch.matmul(tensor, tensor.T, out=m3)

print(y1)
print(y2)
print(y3)


tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [ ]:
# Also have element-wise multiplication which can be done using '*' symbol as well as using torch.mul() method.